# Generated by Django 2.1.1 on 2018-10-20 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('image', models.ImageField(null=True, upload_to='photo/', verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=25)),
                ('mobile', models.CharField(max_length=10)),
                ('gender', models.CharField(max_length=7)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_no', models.CharField(max_length=5)),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=25)),
                ('mobile', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=7)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MyApp.StudentData')),
                ('roll_no', models.CharField(max_length=7)),
                ('math', models.CharField(max_length=3)),
                ('science', models.CharField(max_length=3)),
                ('socal', models.CharField(max_length=3)),
                ('english', models.CharField(max_length=3)),
                ('hindi', models.CharField(max_length=3)),
                ('sanskrit', models.CharField(max_length=3)),
                ('obtain', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6)),
                ('result', models.CharField(max_length=5)),
            ],
        ),
    ]
