# Generated by Django 2.1.1 on 2018-10-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=20)),
                ('mobile', models.IntegerField(max_length=10)),
                ('gender', models.CharField(max_length=6)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
    ]
