# Generated by Django 2.1.1 on 2018-10-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marks',
            fields=[
                ('roll_no', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MyApp.StudentData')),
                ('math', models.CharField(max_length=3)),
                ('science', models.CharField(max_length=3)),
                ('socal', models.CharField(max_length=3)),
                ('english', models.CharField(max_length=3)),
                ('hindi', models.CharField(max_length=3)),
                ('sanskrit', models.CharField(max_length=3)),
                ('obtain', models.DecimalField(decimal_places=2, max_digits=6)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=6)),
            ],
        ),
    ]
