# Generated by Django 2.1.1 on 2018-10-17 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='marks',
            name='id',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='MyApp.StudentData'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='marks',
            name='roll_no',
            field=models.CharField(max_length=5),
        ),
    ]
