# Generated by Django 2.1.1 on 2018-10-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_auto_20181023_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='student_img',
            field=models.ImageField(null=True, upload_to='student/', verbose_name=''),
        ),
    ]
