# Generated by Django 2.1.1 on 2018-10-24 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0003_studentdata_student_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='student_img',
            field=models.ImageField(null=True, upload_to='photo/', verbose_name=''),
        ),
    ]
