# Generated by Django 2.1.1 on 2018-10-04 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0004_auto_20181002_1239'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('sid', models.IntegerField(default=5, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile', models.IntegerField(max_length=10, unique=True)),
                ('gender', models.CharField(max_length=10)),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
            ],
        ),
    ]
