# Generated by Django 2.1.1 on 2018-10-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0005_studentdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdata',
            name='password',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='mobile',
            field=models.IntegerField(unique=True),
        ),
    ]
