# Generated by Django 2.1.1 on 2018-10-05 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0006_auto_20181004_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
