# Generated by Django 2.1.1 on 2018-10-13 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0007_auto_20181005_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='image',
            field=models.CharField(default='', max_length=150),
            preserve_default=False,
        ),
    ]
